name = "Colosseum"
uuid = "22445b90-2740-4147-9227-5e1785e46a65"
authors = ["Gabriel Previato <gabriel.previato@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
